exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - docker-compose.yml
  - "/scripts/"
  - package.json

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

gems:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin
languages: ["es", "en"]
exclude_from_localizations: ["js", "css", "fonts", "img", "_posts"]

# Site settings
title: Codesai
url: https://codesai.aerobatic.io
cover: "/assets/cover.png"
logo: "/assets/logo.png"
permalink: :year/:month/:title

disqus_is_enabled: true
atom_url: https://codesai.aerobatic.io

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-78350023-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

environment: production

clients:
    - name: Grupo Domingo Alonso
      url: https://www.aidacanarias.com/
      logo: ../img/logos/domingo_alonso.png
      description: clients/domingo_alonso.html
    - name: TheMotion
      url: https://www.themotion.com/
      logo: ../img/logos/the_motion.png
      description: clients/the_motion.html
    - name: La Casa de Mis Primos
      url: http://www.lacasademisprimos.com/
      logo: ../img/logos/lcdmp.jpg
      description: clients/la_casa_de_mis_primos.html
    - name: Besepa
      url: http://www.besepa.com/
      logo: ../img/logos/besepa.png
      description: clients/besepa.html
