
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

gems:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin
languages: ["es", "en"]
exclude_from_localizations: ["js", "css", "fonts", "img", "_posts"]

# Site settings
title: Codesai
subtitle: "uppps"
url: "https://codesai.aerobatic.io"
cover: "/assets/cover.png"
logo: "/assets/logo.png"
permalink: :year/:month/:title

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
