exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - docker-compose.yml
  - "/scripts/"
  - package.json

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

gems:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin
languages: ["es", "en"]
exclude_from_localizations: ["js", "css", "fonts", "img", "_posts", "atom.xml", "sitemap.xml"]

# Site settings
title: Codesai
url: https://www.codesai.com
cover: "/assets/cover.png"
logo: "/assets/logo.png"
permalink: :year/:month/:title

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-78350023-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

environment: production

clients:
    - name: Grupo Domingo Alonso
      url: https://www.aidacanarias.com/
      logo: ../img/logos/domingo_alonso.png
      description: clients/domingo_alonso.html
    - name: SaludOnNet
      url: https://www.saludonnet.com/
      logo: ../img/logos/salud_on_net.png
      description: clients/salud_on_net.html
    - name: Antevenio
      url: http://www.antevenio.com/
      logo: ../img/logos/antevenio.png
      description: clients/antevenio.html
    - name: TheMotion
      url: https://www.themotion.com/
      logo: ../img/logos/the_motion.png
      description: clients/the_motion.html
    # - name: Ironhack
    #   url: https://www.ironhack.com/es
    #   logo: ../img/logos/ironhack.png
    #   description: clients/ironhack.html
    # - name: JPG Consultores Energéticos
    #   url: http://www.jpgconsultores.es/
    #   logo: ../img/logos/jpg_consultores_energeticos.png
    #   description: clients/jpg_consultores_energeticos.html
    # - name: Besepa
    #   url: http://www.besepa.com/
    #   logo: ../img/logos/besepa.png
    #   description: clients/besepa.html
    - name: La Casa de Mis Primos
      url: http://www.lacasademisprimos.com/
      logo: ../img/logos/lcdmp.jpg
      description: clients/la_casa_de_mis_primos.html
    # - name: iSQI
    #   url: https://www.isqi.org/
    #   logo: ../img/logos/isqi.png
    #   description: clients/isqi.html
    # - name: La Salle. Universitat Ramon Llul
    #   url: http://www.salleurl.edu/
    #   logo: ../img/logos/la_salle.png
    #   description: clients/la_salle.html