exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - docker-compose.yml
  - "/scripts/"
  - package.json

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

gems:
#  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin
# languages: ["es", "en"]
# exclude_from_localizations: ["js", "css", "fonts", "img", "assets", "_posts", "atom.xml", "sitemap.xml"]

# Site settings
title: Codesai
url: https://www.codesai.com
cover: "/assets/cover.png"
logo: "/assets/logo.png"
permalink: :year/:month/:title

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-78350023-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

environment: production

clients:
    - name: Buyviu
      url: https://buyviu.com/
      logo: ../img/logos/buyviu.png
      description: clients/buyviu.html
    - name: GreenPowerMonitor
      url: http://www.greenpowermonitor.com/
      logo: ../img/logos/gpm.png
      description: clients/gpm.html
    - name: Grupo ASV
      url: http://www.grupoasv.com/es/
      logo: ../img/logos/grupo_asv.png
      description: clients/grupo_asv.html
    - name: Grupo Domingo Alonso
      url: https://www.aidacanarias.com/
      logo: ../img/logos/domingo_alonso.png
      description: clients/domingo_alonso.html
    - name: SaludOnNet
      url: https://www.saludonnet.com/
      logo: ../img/logos/salud_on_net.png
      description: clients/salud_on_net.html
    - name: Antevenio
      url: http://www.antevenio.com/
      logo: ../img/logos/antevenio.png
      description: clients/antevenio.html
    - name: TheMotion
      url: https://www.themotion.com/
      logo: ../img/logos/the_motion.png
      description: clients/the_motion.html
