version: '2'
services:
    web:
        image: jekyll/jekyll:pages
        command: ./scripts/development_build.sh
        ports:
            - "4000:4000"
        volumes:
            - .:/srv/jekyll
