version: '2'
services:
    web:
        privileged: true
        build: .
        command: bash -c "ntpd -s && ./scripts/development_build.sh"
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll:cached